/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#e9003a",
        "primary-dim": "#00d4ec",
        "outline": "#767576",
        "tertiary-container": "#fe1543",
        "on-secondary-fixed": "#004819",
        "tertiary": "#ff7076",
        "surface-container-lowest": "#000000",
        "on-secondary-container": "#e4ffe1",
        "on-tertiary-container": "#000000",
        "secondary-dim": "#4bee74",
        "error-container": "#9f0519",
        "on-surface": "#ffffff",
        "on-surface-variant": "#adaaab",
        "on-primary-container": "#004d57",
        "secondary-container": "#006e2a",
        "surface-bright": "#2c2c2d",
        "on-primary": "#005762",
        "primary-fixed-dim": "#00d4ec",
        "primary": "#81ecff",
        "on-tertiary-fixed": "#3a0007",
        "inverse-primary": "#006976",
        "outline-variant": "#484849",
        "inverse-surface": "#fcf8f9",
        "surface-container-high": "#201f21",
        "surface-container": "#1a191b",
        "secondary-fixed": "#5cfd80",
        "tertiary-fixed-dim": "#ff7a7e",
        "tertiary-fixed": "#ff9193",
        "primary-container": "#00e3fd",
        "error": "#ff716c",
        "on-primary-fixed-variant": "#005762",
        "background": "#0e0e0f",
        "on-background": "#ffffff",
        "surface": "#0e0e0f",
        "on-error-container": "#ffa8a3",
        "secondary-fixed-dim": "#4bee74",
        "on-tertiary-fixed-variant": "#790019",
        "on-tertiary": "#49000b",
        "on-secondary": "#005d22",
        "on-primary-fixed": "#003840",
        "surface-variant": "#262627",
        "primary-fixed": "#00e3fd",
        "surface-container-low": "#131314",
        "error-dim": "#d7383b",
        "secondary": "#5cfd80",
        "on-error": "#490006",
        "surface-container-highest": "#262627",
        "inverse-on-surface": "#565556",
        "surface-dim": "#0e0e0f",
        "on-secondary-fixed-variant": "#006827",
        "surface-tint": "#81ecff"
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
}
